* GOJira
  Add jira issues to org-mode

** Overview
   Import a jira issue into org-mode as a todo.

   Gojira is built on top of [[https://github.com/ahungry/org-jira][org-jira]] and acts as a simpler alternative
   interface for using org-jira. It allows you to use an existing org file and
   import issues as single standalone entities.

   It's currently only one way. Jira->Org. I may someday add the other
   direction, but I doubt it.

** Why?
   I was tired of copying, pasting, and formatting jira tasks into org files.
   Org-jira is neat but it didn't fit the way I wanted to use it. I have
   existing org files and structures I want to continue using. I just want to be
   able to insert a jira task into an org file.

   Questions/comments [[tosh.lyons@gmail.com][tosh.lyons@gmail.com]]

** Install
   Install org-jira from https://github.com/ahungry/org-jira

   Clone this repo somewhere. For example =~/elisp/= and load it with
   use-package
   #+BEGIN_SRC elisp
     (use-package gojira
       :load-path "~/elisp/gojira/"
       :bind (("C-c j" . gojira-insert-issue-as-org)))
   #+END_SRC

   Set your jira url
   #+BEGIN_SRC elisp
     (setq jiralib-url "https://jira.example.com")
   #+END_SRC

** Usage
   To pull an issue from jira into your org file call
   =gojira-insert-issue-as-org=. You will be prompted for the jira issue key and
   the issue will be inserted at the same level as the heading at point.

   It's easiest to map that to a keybinding.

   The install section above binds this command to =C-c j=
** TODOs
*** TODO TODO Make this a proper package
*** TODO TODO Add package to MELPA
*** TODO TODO Add ability to update issues
    Sometimes tasks change. Currently I just delete them and reimport them, but
    it would be nice to be able to just update them, I think.

    I may prefer to just be able to update the comments because I like to make
    notes on the tasks sometimes and it could be hard not to overwrite them on
    update.
